@OrderSystem.API_HostAddress = http://localhost:5255

GET {{OrderSystem.API_HostAddress}}/orders/
Accept: application/json

###

POST {{OrderSystem.API_HostAddress}}/orders
Accept: application/json 
Content-Type: application/json
{
  "customerEmail": "test@test.com",
  "amount": 100
}